[feat] #18 add user signup api call
selfmenagement/front pull request #20
Opened 2023-05-03 12:24 UTC by kobums

## 🍀 개요

회원가입 api call 기능 추가 

## ✏️ 작업 내용

- [x] install axios
- [x] /api/user/signup 호출
- [x] ts eslint error 수정
- [x] signup textfield 컴포넌트
- [x] add signup complete page
- [x] add modal complete

## 🔎 추가 정보

- close #18

2023-05-05 00:09 UTC, 2heeesss approved these changes

2023-05-05 00:09 UTC, 2heeesss commented on src/controllers/application/User.ts
> +import { checkEmail, checkName, checkPw, confirmPw } from '../domain/User';
절대경로로 통일해주세요

2023-05-05 00:09 UTC, 2heeesss commented on src/pages/signup/index.tsx
> +    if (res.result === true) {
`res.result === true` 보다 `res.result`를 사용하는게 더 좋을것같습니다.
그리고 사용하지 않는 콘솔은 지워주세요!

2023-05-05 06:10 UTC, kobums commented on src/controllers/application/User.ts
> +import { checkEmail, checkName, checkPw, confirmPw } from '../domain/User';
수정했습니다.

2023-05-05 06:10 UTC, kobums commented on src/pages/signup/index.tsx
> +    if (res.result === true) {
if 문은 수정했습니다.
콘솔은 page 만들면 수정해서 커밋하도록 하겠습니다.

2023-05-06 12:27 UTC, 2heeesss commented on src/components/organisms/SignupCard.tsx
> +    <>
fragment로 최상위를 감싸는 이유가 혹시 있을까요? stack 태그가 최상위라면 fragment가 필요없을것같아서요!

2023-05-06 14:02 UTC, 2heeesss approved these changes

2023-05-06 14:04 UTC, 2heeesss commented on src/pages/signup/index.tsx
> +  const TextFieldArrayProps: TextFieldProps[] = [
map으로 반복해서 컴포넌트를 만들게 아니라면 배열 말고 객체를 넘기는게 어떨까요?

2023-05-07 06:44 UTC, kobums commented on src/components/organisms/SignupCard.tsx
> +    <>
a5a317427b7575e3c248f5933c5feb0ef4622803 수정 했습니다.

2023-05-07 06:44 UTC, kobums commented on src/pages/signup/index.tsx
> +  const TextFieldArrayProps: TextFieldProps[] = [
a5a317427b7575e3c248f5933c5feb0ef4622803 수정했습니다.

2023-05-08 04:45 UTC, 2heeesss requested changes
테스트

2023-05-08 04:55 UTC, 2heeesss approved these changes
확인했습니다.

2023-05-08 06:22 UTC, 2heeesss approved these changes
확인했습니다

2023-05-08 07:12 UTC, moojecho approved these changes

2023-05-08 07:12 UTC, moojecho approved these changes

2023-05-08 07:14 UTC, merged