Feat/#25/recoil setting,add login api setting
selfmenagement/front pull request #30
Opened 2023-05-11 08:55 UTC by moojecho

## 🍀 개요

mobx 대신 사용할 전역 상태 관리 라이브러리 recoil로 변경, 로그인 API 연동 

## ✏️ 작업 내용

recoil 초기 세팅, 로그인 API 연동 및 로그인 에러 핸들링

## 🔎 추가 정보

![image](https://github.com/selfmenagement/front/assets/107379879/0188d310-a4fb-4aee-b69a-209d470edb57)

![image](https://github.com/selfmenagement/front/assets/107379879/2198ec35-9d8c-4f50-868a-d57a15732eb8)

2023-05-11 13:07 UTC, 2heeesss requested changes

2023-05-11 13:07 UTC, 2heeesss commented on src/controllers/services/api.ts
> +    if (res.status === 200) {
res.status가 200이 아닐때 리턴값이 undefined입니다. 이때 에러핸들링을 추가해주세요

2023-05-11 13:07 UTC, 2heeesss commented on src/controllers/services/api.ts
> +    if (error instanceof AxiosError && error.response) {
위 분기문이 실패했을때 에러핸들링이 안되고있습니다.
예를들어 네트워크 연결이 끊어진 경우, 서버에서 응답을 보내지 않아서 요청시간 초과가 난경우 등등에서 발생할 수 있습니다.
catch문의 else처리도 같이해주세요

2023-05-11 13:07 UTC, 2heeesss commented on src/pages/login/index.tsx
> +  const handleLogin = async () => {
회원가입할때와 동일하게 유효성 검사를 진행해주세요. controller/domain에 유저 인풋 관련 유효성 검사하는 함수가 이미 선언되어있습니다. 이를통해 서버api 요청을 최소화 하는게 좋을것같습니다.

2023-05-11 13:07 UTC, 2heeesss commented on src/pages/login/index.tsx
> +      console.error(error);
로그인 실패했을때 액션이 추가되어야할것같습니다. 또한 테스트용 콘솔은 삭제해주세요

2023-05-11 14:29 UTC, moojecho commented on src/pages/login/index.tsx
> +      console.error(error);
아파

2023-05-11 23:10 UTC, kobums approved these changes
확인했습니다.

2023-05-12 00:39 UTC, 2heeesss approved these changes
확인했습니다~

2023-05-12 00:57 UTC, merged