Feat #31 add todo layout
selfmenagement/front pull request #37
Opened 2023-05-22 05:40 UTC by kobums

## 🍀 개요

add routine template layout

## ✏️ 작업 내용

- [x] routine template page 추가

<img width="747" alt="스크린샷 2023-05-22 오후 2 39 17" src="https://github.com/selfmenagement/front/assets/55486001/0ff1bdf6-668e-4906-9600-f4d0c90c6213">

- [x] routine template add page 추가

<img width="741" alt="스크린샷 2023-05-22 오후 2 38 54" src="https://github.com/selfmenagement/front/assets/55486001/ee4c618f-c1c6-42d4-9f91-2b109daedf96">

## 🔎 추가 정보

- close #31

2023-05-22 06:16 UTC, moojecho approved these changes

2023-05-22 11:01 UTC, 2heeesss requested changes
고생하셨습니다! 모든 리뷰를 적용할필요는 없습니다. 이해가 안되는부분이 있거나 논의가 필요한 부분은 연락주세요

2023-05-22 11:01 UTC, 2heeesss commented on src/components/atoms/DialogAtom.tsx
> +            <ListItemButton
ListItem에서 key 어트리뷰트를 설정했으니 ListItemButton에서는 key값 삭제하는것이 좋을것같습니다

2023-05-22 11:01 UTC, 2heeesss commented on src/components/atoms/DialogAtom.tsx
> +  selectedValue: string;
selectedValue가 어떤 값을 의미하는지 잘 모르겠습니다. 좀 더 명확한 이름으로 바꾸는게 더 좋지않을까요? ex) selectedType

2023-05-22 11:01 UTC, 2heeesss commented on src/components/atoms/MainBody.tsx
> +    <>
Fragment가 꼭 필요하지 않아보입니다!

2023-05-22 11:01 UTC, 2heeesss commented on src/components/atoms/RoutineTemplate.tsx
> +      <CardActions>
cardActions 를 삭제해도 괜찮을것같습니다.
아래와같이 보통 사용하는것으로 보여지는데, 현재 파일에서는 CardContet만 사용해도 동일하게 동작하는것으로 생각이 됩니다.
https://www.geeksforgeeks.org/react-mui-cardactions-api/

2023-05-22 11:01 UTC, 2heeesss commented on src/components/organisms/RoutineTemplateAddText.tsx
> +  const nameChangeHandler = (e: React.ChangeEvent<HTMLInputElement>) => {
다른 핸들들을 작성한것과 비슷하게 handler prefix를 먼저 사용하는게 더 좋을것같습니다!

2023-05-22 11:01 UTC, 2heeesss commented on src/components/organisms/RoutineTemplateAddText.tsx
> +  setName: (arg0: string) => void;
arg0 보다는 name 이 더 좋을것같습니다!
또한, props 타입에 대해서 interface로 만든 파일도 있고, 아닌 파일도 있습니다. 이를 통일하는게 좋을것같습니다.

2023-05-22 11:01 UTC, 2heeesss commented on src/components/organisms/RoutineTemplateAddText.tsx
> +    // borderColor: theme.palette.mode === 'light' ? '#E0E3E7' : '#2D3843',
사용하지않는 주석은 삭제해주세요!

2023-05-22 11:01 UTC, 2heeesss commented on src/components/organisms/RoutineTemplateAddType.tsx
> +  setSelectedType: (arg0: string) => void;
arg0 보다는 type 이 더 좋을것같습니다!
또한, props 타입에 대해서 interface로 만든 파일도 있고, 아닌 파일도 있습니다. 이를 통일하는게 좋을것같습니다.

2023-05-22 11:01 UTC, 2heeesss commented on src/components/organisms/RoutineTemplateAddType.tsx
> +  color: theme.palette.getContrastText('##1A2027'),
#두개쓴것은 오타인가요? 아니면 다른 의미가 있는지 궁금합니다

2023-05-22 11:01 UTC, 2heeesss commented on src/components/organisms/RoutineTemplateAddType.tsx
> +  types: Array<string>;
`dialobAtom` 컴포넌트에서는 배열을 atomitems: string[] 형식으로 사용하고있습니다. 하지만 `RoutineTemplateAddType` 컴포넌트에서는 Array<string> 형식으로, 이 둘을 하나의 방법으로 통일하는게 좋을것같습니다.

2023-05-22 11:01 UTC, 2heeesss commented on src/components/organisms/RoutineTemplateCard.tsx
> +              key={index}
key프로퍼티의 값을 index로 사용하는것은 좋지않습니다! 백엔드 작업 시 Id 제공 예정입니다.

https://react.dev/learn/rendering-lists
You might be tempted to use an item’s index in the array as its key. In fact, that’s what React will use if you don’t specify a key at all. But the order in which you render items will change over time if an item is inserted, deleted, or if the array gets reordered. Index as a key often leads to subtle and confusing bugs.

Similarly, do not generate keys on the fly, e.g. with key={Math.random()}. This will cause keys to never match up between renders, leading to all your components and DOM being recreated every time. Not only is this slow, but it will also lose any user input inside the list items. Instead, use a stable ID based on the data.

Note that your components won’t receive key as a prop. It’s only used as a hint by React itself. If your component needs an ID, you have to pass it as a separate prop: <Profile key={id} userId={id} />.

2023-05-22 11:01 UTC, 2heeesss commented on src/components/organisms/RoutineTemplateCard.tsx
> +      const onWheel = (e: any) => {
wheel 이벤트라면 WheelEvent 타입으로 설정하는게 좋을것같습니다. 혹시 any로 넣은 이유가 있을까요?

2023-05-22 11:01 UTC, 2heeesss commented on src/pages/routine/template/add.tsx
> +const types = ['time', 'count'];
types는 이 파일에서밖에 사용되지않는건가요? (그냥 궁금해서 물어보는것)

2023-05-22 11:01 UTC, 2heeesss commented on src/pages/routine/template/index.tsx
> +            key={index}
key프로퍼티의 값을 index로 사용하는것은 좋지않습니다! 백엔드 작업 시 Id 제공 예정입니다.

2023-05-22 11:01 UTC, 2heeesss requested changes
고생하셨습니다! 모든 리뷰를 적용할필요는 없습니다. 이해가 안되는부분이 있거나 논의가 필요한 부분은 연락주세요

2023-05-22 14:45 UTC, kobums commented on src/components/atoms/DialogAtom.tsx
> +            <ListItemButton
네 수정했습니다.

2023-05-22 14:49 UTC, kobums commented on src/components/atoms/DialogAtom.tsx
> +  selectedValue: string;
dialog 에서 items중에 선택한 값이므로 item은 여러가지가 올 수 있으므로 selectedItem 으로 변경했습니다.

2023-05-22 14:50 UTC, kobums commented on src/components/atoms/MainBody.tsx
> +    <>
수정했습니다.

2023-05-22 15:06 UTC, kobums commented on src/components/atoms/RoutineTemplate.tsx
> +      <CardActions>
넵 동일하게 동작하지만 삭제하면 css를 수정 하는관계로 그냥 놔두도록 하겠습니다.

2023-05-22 15:07 UTC, kobums commented on src/components/organisms/RoutineTemplateCard.tsx
> +              key={index}
key 값을 설정하지 않으면 error 때문에 작업할 수 있어서 index를 사용했습니다.
백엔드 작업시 제공된 ID를 적용할 예정입니다.

2023-05-22 15:08 UTC, kobums commented on src/components/organisms/RoutineTemplateAddType.tsx
> +  types: Array<string>;
하나의 방식으로 통일했습니다.

2023-05-22 15:09 UTC, kobums commented on src/components/organisms/RoutineTemplateCard.tsx
> +      const onWheel = (e: any) => {
WheelEvent 타입을 몰라서 any로 넣었습니다. 수정했습니다.

2023-05-22 15:10 UTC, kobums commented on src/pages/routine/template/add.tsx
> +const types = ['time', 'count'];
이 파일에서만 사용합니다.
types는 백엔드에서 받아서 할 내용입니다.

2023-05-22 15:11 UTC, kobums commented on src/pages/routine/template/index.tsx
> +            key={index}
key 값을 설정하지 않으면 error 때문에 작업할 수 있어서 index를 사용했습니다.
백엔드 작업시 제공된 ID를 적용할 예정입니다.

2023-05-22 15:17 UTC, kobums commented on src/components/organisms/RoutineTemplateAddType.tsx
> +  color: theme.palette.getContrastText('##1A2027'),
오타입니다 수정했습니다.

2023-05-22 15:18 UTC, kobums commented on src/components/organisms/RoutineTemplateAddText.tsx
> +    // borderColor: theme.palette.mode === 'light' ? '#E0E3E7' : '#2D3843',
넵 수정했습니다.

2023-05-22 15:45 UTC, kobums commented on src/components/organisms/RoutineTemplateAddText.tsx
> +  setName: (arg0: string) => void;
수정했습니다.

2023-05-22 15:45 UTC, kobums commented on src/components/organisms/RoutineTemplateAddType.tsx
> +  setSelectedType: (arg0: string) => void;
수정했습니다.

2023-05-22 15:52 UTC, kobums commented on src/components/organisms/RoutineTemplateAddText.tsx
> +  const nameChangeHandler = (e: React.ChangeEvent<HTMLInputElement>) => {
수정했습니다.

2023-05-23 05:04 UTC, 2heeesss approved these changes
확인했습니다! 컨플릭만 해결하고 머지하면 될것같습니다

2023-05-23 12:34 UTC, kobums commented
conflict 수정했습니다

2023-05-23 12:34 UTC, merged