Feat/#34/add main,do,setting page layout
selfmenagement/front pull request #39
Opened 2023-05-23 05:37 UTC by moojecho

## ✏️ 작업 내용

routine, detail page layout 및 refactoring 

## 🔎 추가 정보
routine page-
![image](https://github.com/selfmenagement/front/assets/107379879/1bd2e975-f2b8-4dc2-8f85-0ee3d29a540b)`

routine/detail page-
![image](https://github.com/selfmenagement/front/assets/107379879/310b6db0-9780-4a41-9ffa-2badb884a8e4)

my page-
![image](https://github.com/selfmenagement/front/assets/107379879/3102758c-c308-4bcb-b476-f2de62958e49)

2023-05-23 12:40 UTC, kobums approved these changes

2023-05-24 05:29 UTC, 2heeesss requested changes
고생하셨습니다! 리뷰에 남긴것은 무조건 적용할 필요는 없습니다. 개인적인 의견이니 이해가 가지 않는점이 있다면 코멘트로 남겨주세요

2023-05-24 05:29 UTC, 2heeesss commented on src/components/organisms/RoutineCard.tsx
> +    <>
fragment는 삭제해도 될것같습니다

2023-05-24 05:29 UTC, 2heeesss commented on src/components/organisms/index.ts
> +export { default as Header } from './Header';
index.ts 삭제하는것은 지금 열려있는 pull request에서 작업할 예정인가요? 아니면 다른 issue로 작업할 예정인가요?

2023-05-24 05:29 UTC, 2heeesss commented on src/components/atoms/CustomButton.tsx
> +  type:
Position 타입을 따로 작성한것과 마찬가지로 type의 타입도 따로 작성하는게 좋을것같습니다. 방법을 통일해주세요

2023-05-24 05:29 UTC, 2heeesss commented on src/components/atoms/LoginBody.tsx
> +  flexDirection?: 'row' | 'column';
'row' | 'column' 타입이 반복되고있습니다. 재사용가능한 인터페이스로 분리하는건 어떨까요?

2023-05-24 05:29 UTC, 2heeesss commented on src/components/atoms/MyInfo.tsx
> +  title?: string;
title이나 content가 undefined일 때가 있나요? 항상 title, content가 있어야하는것같은데 선택속성으로 만든 이유가 궁금합니다!

2023-05-24 05:30 UTC, moojecho commented on src/components/organisms/index.ts
> +export { default as Header } from './Header';
현재 issue 작업 해서 commit 해뒀습니다.

2023-05-24 05:32 UTC, moojecho commented on src/components/atoms/MyInfo.tsx
> +  title?: string;
해당 issue 초기 단계에서 작성했던 코드라 깜빡하고 수정 못했던 부분입니다.
수정했습니다.

2023-05-24 05:33 UTC, moojecho commented on src/components/atoms/CustomButton.tsx
> +  type:
통일 시켜줬습니다.

2023-05-24 05:46 UTC, moojecho commented on src/components/atoms/LoginBody.tsx
> +  flexDirection?: 'row' | 'column';
말씀하신게 두 타입 정의를 하나로 합치라는 말씀이실까요?

2023-05-24 05:52 UTC, 2heeesss commented on src/components/atoms/LoginBody.tsx
> +  flexDirection?: 'row' | 'column';
StyledContentProps 인터페이스, LoginBodyProps 인터페이스에서 row | column을 반복해서 사용하고있는것을 인터페이스로 만들자는 의미였습니다.

예를들어
type TflexDirection =  'row' | 'column' 이런식으로 말이죠. customButton 컴포넌트의 position 타입과 같습니다.

2023-05-24 09:04 UTC, 2heeesss approved these changes
고생하셨습니다!

2023-05-25 04:54 UTC, merged